export const urls = {
    INDEX: '/',
    LOGIN: "/login",
    ORDERS: '/orders',
    DASHBOARD: "/DASHBOARD",
    DRIVERS: '/drivers',
    EMPLOYES: '/employes',
    ARIZALAR: '/arizalar',
    ORDERSDRIVERS: '/orders-drivers',
    TRAFFICS: '/traffics',
    SETTINGS: '/settings',
    STUDENTS: '/students',
    CREATE_DRIVER: '/create-driver',
    CREATE_STUDENT: '/create-student/:id',
    ADD_STUDENT: '/add-student/',
    CREATE_ARIZA: '/create-ariza',
    EDIT_DRIVER: '/edit-driver/:id',
    DETAIL_DRIVER: '/detail-driver/:id',
    FLOOR_DETAIL: '/floor-detail/:id',
    ROOM_DETAIL: '/room-detail/:id',
    CLIENTS: '/clients',
    CREATE_ORDER: '/create-order',
};